spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    # password: '{cipher}ed092f20c6a815b4d21b03657aaebca2d2d4be9227013e07796df08c63f18eec'
    password: 1234

token:
  expiration_time: 864000000
  secret: applicationrherthyjhjtythrjyjhertjh43e5hkguwhegkjdrhgoizegtwa3ytawn33

gateway:
  ip: 172.20.0.8

order-service:
  url: http://ORDER-SERVICE/order-service/%s/orders
  exception:
    order_is_empty: User's Order is Empty!!
